/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample03;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public boolean someLibraryMethod02() {
        return false;
    }
}
