/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample03.bat.service;

import static org.junit.Assert.*;

import org.junit.Test;

public class SampleServiceTest {
    @Test
    public void TestExec01() {
    	SampleService service = new SampleService();
        assertNull("someLibraryMethod should return 'true'", service.search());

        assertNotNull("someLibraryMethod should return 'true'", service.executeFirst());

        assertNotNull("someLibraryMethod should return 'true'", service.executeSecond());

        assertNotNull("someLibraryMethod should return 'true'", service.executeFinish());

    }
}
