/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample03.bat.service;

import static org.junit.Assert.*;

import org.junit.Test;

public class SampleServiceTest {
    @Test
    public void testSomeLibraryMethod() {
    	SampleService service = new SampleService();
        assertNull("someLibraryMethod should return 'true'", service.search());
    }
}
